name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
      - ft-auto-deploy

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4